Update figures
theislab/cellrank_notebooks pull request #75
Opened 2024-09-26 15:27 UTC by WeilerP

## Changes

- Update overview figures
- Update kernel choice figure and add dark mode version
- Update the getting started tutorial to support dark mode for kernel choice figure

## Related issues

Closes #74.

2024-09-26 15:58 UTC, michalk8 requested changes
Minor fixes, then LGTM! Thanks @WeilerP !

2024-09-26 15:58 UTC, michalk8 commented on tutorials/_static/img/100_cellrank_kernels.png
I'd suggest having the `light_mode` postfix for consistency.

2024-09-26 15:58 UTC, michalk8 commented on tutorials/_static/img/100_cellrank_overview_dark_mode.png
I think the dark mode PNG is again bigger than the light mode (3352x1708 vs 1846x941).

2024-09-26 15:58 UTC, michalk8 commented on tutorials/general/100_getting_started.ipynb
> +    ":::{image} ../_static/img/100_cellrank_kernels_mode.png\n",
Think this should be `100_cellrank_kernels_dark_mode.png`.

2024-09-26 15:58 UTC, michalk8 commented on tutorials/_static/img/100_cellrank_overview.png
Would also consider renaming to `100_cellrank_overview_light_mode.png` for consistency + updating the links in the notebook(s).

2024-09-26 15:58 UTC, michalk8 commented on tutorials/general/100_getting_started.ipynb
> +    ":::{figure-md} fig-structure\n",
Please remove the `:::{figure-md} fig-structure` part - there are now 2 images being rendered.

2024-09-26 19:47 UTC, WeilerP commented on tutorials/_static/img/100_cellrank_overview_dark_mode.png
Yes, strange. I fixed it.

2024-09-27 09:16 UTC, michalk8 approved these changes
LGTM, thanks a lot!

2024-09-27 09:23 UTC, Marius1311 approved these changes
Looks great!

2024-09-27 11:54 UTC, merged